### PR TITLE
Place under BSD license.

### PR DESCRIPTION
**Pull request by cpressey**
Hi @pro465 

I thought this project was already under an open-source license but it turns out it wasn't.

I'd like to put it under an open-source license.  Since you've already contributed to it, you should have a say in that.

I'm proposing to put it under this BSD license, in which you're listed as a copyright holder.

If you'd rather not be listed as a copyright holder, let me know and I'll remove that line.

Or if you'd rather the entire project be placed in the public domain instead, I'd be fine with that, just let me know.

Thanks!

### CODE REVIEW

**Comment by pro465** [comment]
are the examples in public domain? 
If so, I'm good 👍

**Comment by pro465** [comment]
on second thought, I don't wanna be listed as a copyright holder.

**Comment by cpressey** [comment]
OK - I've removed your name, I've moved the LICENSE to the `src` directory to indicate that it applies to the code only, and added an UNLICENSE to the `eg` directory to indicate they're in the public domain.

**Comment by pro465** [comment]
looks good to me 👍 , thanks for the modifications

**Pull request merged**
