### PR TITLE
fix #5

### LINKED ISSUE #4: inconsistency?
in the propositional algebra file, you have this axiom as modus ponens: 
[https://github.com/catseye/Eqthy/blob/3a7bb427a58bed740605e37445817f0f54485c9f/eg/propositional-algebra.eqthy.md?plain=1#L31](https://github.com/catseye/Eqthy/blob/3a7bb427a58bed740605e37445817f0f54485c9f/eg/propositional-algebra.eqthy.md?plain=1#L31)

i believe that leads to inconsistency, as the equal sign means that we can deduce the "converse" too, which means we can deduce `th(P, th(impl(P, Q), e))` from `th(Q, e)` **for all `P`**, which is bad

### LINKED ISSUE #5: inconsistency again, but potentially more problematic
here:

https://github.com/catseye/Eqthy/blob/3a7bb427a58bed740605e37445817f0f54485c9f/eg/boolean-algebra.eqthy.md?plain=1#L177-L178

that means, by transitivity:

    not(not(A)) = or(not(not(A)), 1) = 1

which is false.

I'm not sure which theorem says this, since you did not give a hint here. However, I _can_ say that whichever theorem says that is false. 

this means if Eqthy accepted this, either:
1. the axiomization is wrong (I did not find anything suspicious about them, but idk)
2. proof checker implementation is wrong. (did not check, because I am not that great at Python)
3. Eqthy or equational logic or boolean algebra is wrong (unlikely)

### PR DESCRIPTION
**Pull request by pro465**
this PR fixes #5 by correctly erroring out instead of deriving incorrect eqs. However, it does not fix the incorrect proof in question.

### CODE REVIEW

**Comment by pro465** [comment]
oops, i made some nonsensical merges because i was trying to specify it fixes #5 not #4...

**Comment by pro465** [comment]
i fixed the theorem now btw

**Comment by pro465** [comment]
@cpressey ?

**Comment by cpressey** [comment]
I've had time to look at this now, but not to think about it very much.

Based on the change to `term.py` in this PR, it looks like the underlying bug is simply that when pattern matching two terms, it isn't requiring that they have the same constructors (which is... most definitely a bug!)

Thank you for finding this, I'll try to get it merged in soon.

**Pull request merged**
